import {BadRequestException,ForbiddenException,Injectable,NotFoundException} from '@nestjs/common';
import {InjectRepository} from '@nestjs/typeorm';
import {DataSource,Repository} from 'typeorm';
import {Room} from '../rooms/room.entity';import {RoomMember} from './room-member.entity';import {Message} from './message.entity';import {RoomRead} from './room-read.entity';import {ModerationAudit} from './moderation-audit.entity';import {RoomBan} from './room-ban.entity';import {User} from '../auth/user.entity';import {assertCanAct} from '../common/rank-policy';import {MediaService} from '../media/media.service';import {MediaAsset} from '../media/media.entity';
@Injectable() export class MessagesService{
 constructor(@InjectRepository(Room)private rooms:Repository<Room>,@InjectRepository(RoomMember)private members:Repository<RoomMember>,@InjectRepository(Message)private messages:Repository<Message>,@InjectRepository(RoomRead)private reads:Repository<RoomRead>,@InjectRepository(User)private users:Repository<User>,@InjectRepository(ModerationAudit)private audits:Repository<ModerationAudit>,@InjectRepository(RoomBan)private bans:Repository<RoomBan>,private db:DataSource,private media:MediaService){}
 async join(roomId:string,userId:string){return this.db.transaction(async em=>{const room=await em.findOne(Room,{where:{id:roomId},lock:{mode:'pessimistic_write'}});if(!room)throw new NotFoundException('Oda bulunamadı');const ban=await em.findOneBy(RoomBan,{roomId,userId});if(ban&&(!ban.expiresAt||ban.expiresAt>new Date()))throw new ForbiddenException('Bu odadan yasaklandın');if(ban?.expiresAt&&ban.expiresAt<=new Date())await em.remove(RoomBan,ban);if(room.isLocked)throw new ForbiddenException('Oda kilitli');const existing=await em.findOneBy(RoomMember,{roomId,userId});if(existing)return existing;const count=await em.count(RoomMember,{where:{roomId}});if(count>=room.maxMembers)throw new BadRequestException('Oda dolu');return em.save(RoomMember,em.create(RoomMember,{roomId,userId}));});}
 async listMembers(roomId:string,userId:string){await this.requireMember(roomId,userId);const rows=await this.members.find({where:{roomId},order:{joinedAt:'ASC'}});const ids=rows.map(x=>x.userId);if(!ids.length)return[];const users=await this.users.createQueryBuilder('u').leftJoinAndSelect('u.rank','rank').where('u.id IN (:...ids)',{ids}).getMany();return users.map(u=>({id:u.id,username:u.username,rank:u.rank}));}
 async history(roomId:string,userId:string,limit=50,before?:string){await this.requireMember(roomId,userId);let anchor:Message|undefined;if(before){anchor=await this.messages.findOneBy({id:before,roomId})??undefined;if(!anchor)throw new BadRequestException('Geçersiz mesaj cursor');}const take=Math.min(limit,100);const qb=this.messages.createQueryBuilder('m').where('m.room_id=:roomId',{roomId}).orderBy('m.created_at','DESC').addOrderBy('m.id','DESC').take(take+1);if(anchor)qb.andWhere('(m.created_at < :created OR (m.created_at = :created AND m.id < :id))',{created:anchor.createdAt,id:anchor.id});const raw=await qb.getMany();const hasMore=raw.length>take;const items=raw.slice(0,take).reverse();return{items:await this.hydrate(items),hasMore,nextCursor:hasMore?items[0]?.id??null:null};}
 async send(roomId:string,userId:string,body:string|undefined,clientId:string,replyToId?:string,mediaAssetId?:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(clientId))throw new BadRequestException('Geçersiz clientId');const membership=await this.requireMember(roomId,userId);if(membership.mutedUntil&&membership.mutedUntil>new Date())throw new ForbiddenException(`Susturma ${membership.mutedUntil.toISOString()} tarihine kadar aktif`);const clean=(body??'').trim();if(!clean&&!mediaAssetId)throw new BadRequestException('Mesaj veya medya gerekli');let reply:Message|null=null;if(replyToId){reply=await this.messages.findOneBy({id:replyToId,roomId});if(!reply||reply.deletedAt)throw new BadRequestException('Yanıtlanan mesaj bulunamadı');}const existing=await this.messages.findOneBy({userId,clientId});if(existing){if(existing.roomId!==roomId)throw new BadRequestException('clientId başka odada kullanılmış');return (await this.hydrate([existing]))[0];}try{return await this.db.transaction(async em=>{const saved=await em.getRepository(Message).save(em.getRepository(Message).create({roomId,userId,body:clean,clientId,replyToId:reply?.id??null,mediaAssetId:mediaAssetId??null}));if(mediaAssetId)await this.media.claim(em,userId,mediaAssetId,'room','room_message',saved.id);return (await this.hydrate([saved]))[0];});}catch(e:any){if(String(e?.code)==='23505'){const retry=await this.messages.findOneBy({userId,clientId});if(retry&&retry.roomId===roomId)return (await this.hydrate([retry]))[0];}throw e;}}

 async edit(roomId:string,userId:string,messageId:string,body:string){await this.requireMember(roomId,userId);const m=await this.messages.findOneBy({id:messageId,roomId});if(!m||m.deletedAt)throw new NotFoundException('Mesaj bulunamadı');if(m.userId!==userId)throw new ForbiddenException('Yalnızca kendi mesajını düzenleyebilirsin');const clean=body.trim();if(!clean)throw new BadRequestException('Boş mesaj kaydedilemez');m.body=clean;m.editedAt=new Date();return (await this.hydrate([await this.messages.save(m)]))[0];}
 async remove(roomId:string,actorId:string,messageId:string,reason?:string){await this.requireMember(roomId,actorId);return this.db.transaction(async em=>{const m=await em.findOne(Message,{where:{id:messageId,roomId},lock:{mode:'pessimistic_write'}});if(!m||m.deletedAt)throw new NotFoundException('Mesaj bulunamadı');if(m.userId!==actorId){const [actor,target]=await Promise.all([em.findOne(User,{where:{id:actorId},relations:{rank:true}}),em.findOne(User,{where:{id:m.userId},relations:{rank:true}})]);if(!actor||!target)throw new NotFoundException('Kullanıcı bulunamadı');assertCanAct(actor,target,'room.moderateMessages');await em.save(ModerationAudit,em.create(ModerationAudit,{actorId,targetUserId:target.id,roomId,messageId:m.id,action:'message.delete',reason:reason?.trim()||null,metadata:{targetStars:target.rank.starCount}}));}m.deletedAt=new Date();m.body='';return {id:(await em.save(Message,m)).id,roomId,deletedAt:m.deletedAt};});}
 async audit(roomId:string,userId:string,limit=50){await this.requireMember(roomId,userId);const actor=await this.users.findOne({where:{id:userId},relations:{rank:true}});if(!actor?.rank?.permissions?.['room.audit'])throw new ForbiddenException('Denetim kayıtlarını görme yetkin yok');return this.audits.find({where:{roomId},order:{createdAt:'DESC'},take:Math.min(Math.max(limit,1),100)});}
 async markRead(roomId:string,userId:string,messageId:string){await this.requireMember(roomId,userId);const message=await this.messages.findOneBy({id:messageId,roomId});if(!message)throw new BadRequestException('Mesaj bu odaya ait değil');await this.reads.upsert({roomId,userId,lastReadMessageId:messageId,lastReadAt:new Date()},['roomId','userId']);return{ok:true,messageId};}
 async unread(roomId:string,userId:string){await this.requireMember(roomId,userId);const read=await this.reads.findOneBy({roomId,userId});if(!read?.lastReadMessageId)return{count:await this.messages.count({where:{roomId}})};const anchor=await this.messages.findOneBy({id:read.lastReadMessageId,roomId});if(!anchor)return{count:await this.messages.count({where:{roomId}})};const count=await this.messages.createQueryBuilder('m').where('m.room_id=:roomId',{roomId}).andWhere('(m.created_at > :created OR (m.created_at = :created AND m.id > :id))',{created:anchor.createdAt,id:anchor.id}).getCount();return{count};}
 async assertMember(roomId:string,userId:string){return this.requireMember(roomId,userId);}
 private async hydrate(items:Message[]){const ids=[...new Set(items.map(x=>x.userId))];const users=ids.length?await this.users.createQueryBuilder('u').leftJoinAndSelect('u.rank','rank').where('u.id IN (:...ids)',{ids}).getMany():[];const map=new Map(users.map(u=>[u.id,u]));const mediaIds=items.map(x=>x.mediaAssetId).filter((x):x is string=>!!x);const media=mediaIds.length?await this.db.getRepository(MediaAsset).createQueryBuilder('a').where('a.id IN (:...ids) AND a.deleted_at IS NULL',{ids:mediaIds}).getMany():[];const mediaMap=new Map(media.map(a=>[a.id,a]));return items.map(m=>({id:m.id,clientId:m.clientId,body:m.deletedAt?'':m.body,media:m.deletedAt||!m.mediaAssetId?null:(()=>{const a=mediaMap.get(m.mediaAssetId!);return a?{id:a.id,publicUrl:a.publicUrl,mimeType:a.mimeType,sizeBytes:a.sizeBytes}:null})(),replyToId:m.replyToId,editedAt:m.editedAt,deletedAt:m.deletedAt,createdAt:m.createdAt,user:{id:m.userId,username:map.get(m.userId)?.username??'Kullanıcı',rank:map.get(m.userId)?.rank??null}}));}
 async moderate(roomId:string,actorId:string,targetUserId:string,action:'mute'|'unmute'|'kick'|'ban'|'unban',durationMinutes?:number,reason?:string){await this.requireMember(roomId,actorId);return this.db.transaction(async em=>{const [actor,target]=await Promise.all([em.findOne(User,{where:{id:actorId},relations:{rank:true}}),em.findOne(User,{where:{id:targetUserId},relations:{rank:true}})]);if(!actor||!target)throw new NotFoundException('Kullanıcı bulunamadı');const permission=action==='mute'||action==='unmute'?'room.mute':action==='kick'?'room.kick':'room.ban';assertCanAct(actor,target,permission);const member=await em.findOne(RoomMember,{where:{roomId,userId:targetUserId},lock:{mode:'pessimistic_write'}});const existingBan=await em.findOne(RoomBan,{where:{roomId,userId:targetUserId},lock:{mode:'pessimistic_write'}});
 if(action==='mute'){if(!member)throw new NotFoundException('Hedef kullanıcı odada değil');const mins=Math.min(Math.max(durationMinutes??10,1),10080);member.mutedUntil=new Date(Date.now()+mins*60000);await em.save(RoomMember,member);}
 if(action==='unmute'){if(!member)throw new NotFoundException('Hedef kullanıcı odada değil');member.mutedUntil=null;await em.save(RoomMember,member);}
 if(action==='kick'){if(!member)throw new NotFoundException('Hedef kullanıcı odada değil');await em.remove(RoomMember,member);}
 if(action==='ban'){const mins=durationMinutes?Math.min(Math.max(durationMinutes,1),10080):undefined;const expiresAt=mins?new Date(Date.now()+mins*60000):null;if(existingBan){existingBan.actorId=actorId;existingBan.reason=reason?.trim()||null;existingBan.expiresAt=expiresAt;await em.save(RoomBan,existingBan);}else await em.save(RoomBan,em.create(RoomBan,{roomId,userId:targetUserId,actorId,reason:reason?.trim()||null,expiresAt}));if(member)await em.remove(RoomMember,member);}
 if(action==='unban'){if(!existingBan)throw new NotFoundException('Aktif yasak bulunamadı');await em.remove(RoomBan,existingBan);}
 await em.save(ModerationAudit,em.create(ModerationAudit,{actorId,targetUserId,roomId,messageId:null,action:`room.${action}`,reason:reason?.trim()||null,metadata:{actorStars:actor.rank.starCount,targetStars:target.rank.starCount,durationMinutes:durationMinutes??null}}));return{ok:true,roomId,targetUserId,action,forceLeave:action==='kick'||action==='ban'};});}
 private async requireMember(roomId:string,userId:string){const member=await this.members.findOneBy({roomId,userId});if(!member)throw new ForbiddenException('Önce odaya katılmalısın');return member;}

}
