import {BadRequestException,ForbiddenException,Injectable,NotFoundException} from '@nestjs/common';import {InjectRepository} from '@nestjs/typeorm';import {DataSource,In,Repository} from 'typeorm';import {User} from '../auth/user.entity';import {Profile} from '../profiles/profile.entity';import {DirectConversation,DirectConversationMember,DirectMessage} from './dm.entity';
import {MediaService}from '../media/media.service';import{PreferencesService}from'../preferences/preferences.service';import {MediaAsset}from '../media/media.entity';import{NotificationsService}from'../notifications/notifications.service';
@Injectable()export class DmService{constructor(@InjectRepository(User)private users:Repository<User>,@InjectRepository(DirectConversation)private convs:Repository<DirectConversation>,@InjectRepository(DirectConversationMember)private members:Repository<DirectConversationMember>,@InjectRepository(DirectMessage)private messages:Repository<DirectMessage>,private db:DataSource,private media:MediaService,private prefs:PreferencesService,private notifications:NotificationsService){}
 private pair(a:string,b:string){return[a,b].sort().join(':')}
 async open(actorId:string,otherId:string){if(actorId===otherId)throw new BadRequestException('Kendine mesaj gönderemezsin');if(!await this.users.existsBy({id:otherId}))throw new NotFoundException();if(!await this.prefs.canReceiveDm(otherId))throw new ForbiddenException('Bu kullanıcı özel mesajları kapatmış.');return this.db.transaction(async m=>{const pairKey=this.pair(actorId,otherId);await m.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`dm:${pairKey}`]);const repo=m.getRepository(DirectConversation);let c=await repo.findOneBy({pairKey});if(!c){c=await repo.save(repo.create({pairKey}));await m.createQueryBuilder().insert().into(DirectConversationMember).values([{conversationId:c.id,userId:actorId,lastReadAt:null,lastReadMessageId:null},{conversationId:c.id,userId:otherId,lastReadAt:null,lastReadMessageId:null}]).orIgnore().execute();}return c;});}
 async assertMember(userId:string,id:string){if(!await this.members.existsBy({conversationId:id,userId}))throw new ForbiddenException('Bu konuşmaya erişemezsin')}
 async memberIds(id:string){return(await this.members.findBy({conversationId:id})).map(x=>x.userId)}
 async list(actorId:string){const mine=await this.members.findBy({userId:actorId});if(!mine.length)return[];const ids=mine.map(x=>x.conversationId),rows=await this.convs.find({where:{id:In(ids)},order:{updatedAt:'DESC'}});return Promise.all(rows.map(async c=>{const membership=mine.find(x=>x.conversationId===c.id)!;const peerMember=await this.members.createQueryBuilder('m').where('m.conversationId=:c AND m.userId<>:u',{c:c.id,u:actorId}).getOne();const peer=peerMember?await this.users.findOne({where:{id:peerMember.userId},relations:{rank:true}}):null;const profile=peer?await this.db.getRepository(Profile).findOneBy({userId:peer.id}):null;const last=await this.messages.findOne({where:{conversationId:c.id},order:{createdAt:'DESC'}});const unread=await this.unreadCount(actorId,c.id);return{id:c.id,updatedAt:c.updatedAt,peer:peer?{id:peer.id,username:peer.username,rank:peer.rank,displayName:profile?.displayName??null,avatarUrl:profile?.avatarUrl??null}:null,lastMessage:last,unreadCount:unread};}));}
 async history(actorId:string,id:string,before?:string){await this.assertMember(actorId,id);const q=this.messages.createQueryBuilder('m').where('m.conversationId=:id AND m.deletedAt IS NULL',{id}).orderBy('m.createdAt','DESC').addOrderBy('m.id','DESC').take(50);if(before){const cursor=await this.messages.findOneBy({id:before,conversationId:id});if(cursor)q.andWhere('(m.createdAt < :at OR (m.createdAt = :at AND m.id < :mid))',{at:cursor.createdAt,mid:cursor.id});}const rows=await q.getMany();rows.reverse();return{items:await Promise.all(rows.map(x=>this.hydrate(x))),nextCursor:rows.length===50?rows[0].id:null};}
 async send(actorId:string,id:string,clientId:string,body:string|undefined,mediaAssetId?:string){await this.assertMember(actorId,id);const peer=(await this.memberIds(id)).find(x=>x!==actorId);if(peer&&!await this.prefs.canReceiveDm(peer))throw new ForbiddenException('Bu kullanıcı özel mesajları kapatmış.');const clean=(body??'').trim();if(!clean&&!mediaAssetId)throw new BadRequestException('Mesaj veya medya gerekli');const prior=await this.messages.findOneBy({senderId:actorId,clientId});if(prior)return this.hydrate(prior);return this.db.transaction(async m=>{const msg=await m.getRepository(DirectMessage).save(m.getRepository(DirectMessage).create({conversationId:id,senderId:actorId,clientId,body:clean,mediaAssetId:mediaAssetId??null}));if(mediaAssetId)await this.media.claim(m,actorId,mediaAssetId,'dm','direct_message',msg.id);await m.getRepository(DirectConversation).update(id,{updatedAt:new Date()});const hydrated=await this.hydrate(msg,m);if(peer)await this.notifications.create(peer,'dm.message',actorId,{conversationId:id,messageId:msg.id});return hydrated;});}
 async markRead(actorId:string,id:string,messageId:string){await this.assertMember(actorId,id);const msg=await this.messages.findOneBy({id:messageId,conversationId:id});if(!msg)throw new NotFoundException('Mesaj bulunamadı');const readAt=new Date();await this.members.update({conversationId:id,userId:actorId},{lastReadAt:readAt,lastReadMessageId:messageId});return{messageId,readAt};}
 async unreadCount(actorId:string,id:string){const m=await this.members.findOneBy({conversationId:id,userId:actorId});if(!m)throw new ForbiddenException();const q=this.messages.createQueryBuilder('x').where('x.conversationId=:id AND x.senderId<>:u AND x.deletedAt IS NULL',{id,u:actorId});if(m.lastReadAt)q.andWhere('x.createdAt > :at',{at:m.lastReadAt});return q.getCount();}

 private async hydrate(msg:DirectMessage,manager?:any){if(!msg.mediaAssetId)return{...msg,media:null};const repo=manager?manager.getRepository(MediaAsset):this.db.getRepository(MediaAsset);const a=await repo.findOneBy({id:msg.mediaAssetId});return{...msg,media:a&&!a.deletedAt?{id:a.id,publicUrl:a.publicUrl,mimeType:a.mimeType,sizeBytes:a.sizeBytes}:null};}
}
