import {ForbiddenException,Injectable,NotFoundException} from '@nestjs/common';import {InjectRepository}from'@nestjs/typeorm';import {IsNull,Repository}from'typeorm';import {User}from'../auth/user.entity';import {Rank}from'../ranks/rank.entity';import {Room}from'../rooms/room.entity';import {Message}from'../messages/message.entity';import {ModerationAudit}from'../messages/moderation-audit.entity';import {SiteSetting}from'./site-setting.entity';import {WallPost,WallComment}from'../social/wall.entity';import {assertCanGrantRank}from'../common/rank-policy';import {SetUserRankDto,UpdateRankDto,UpdateRoomDto,UpdateSettingDto}from'./admin.dto';
@Injectable()export class AdminService{constructor(@InjectRepository(User)private users:Repository<User>,@InjectRepository(Rank)private ranks:Repository<Rank>,@InjectRepository(Room)private rooms:Repository<Room>,@InjectRepository(Message)private messages:Repository<Message>,@InjectRepository(ModerationAudit)private audits:Repository<ModerationAudit>,@InjectRepository(SiteSetting)private settings:Repository<SiteSetting>,@InjectRepository(WallPost)private wallPosts:Repository<WallPost>,@InjectRepository(WallComment)private wallComments:Repository<WallComment>){}
private async actor(id:string){const u=await this.users.findOne({where:{id},relations:{rank:true}});if(!u)throw new NotFoundException();if(!u.rank.permissions?.['admin.access'])throw new ForbiddenException('Admin erişimin yok.');return u}private permit(a:User,p:string){if(!a.rank.permissions?.[p]&&!a.rank.permissions?.['admin.all'])throw new ForbiddenException('Bu admin işlemi için yetkin yok.');}
async overview(id:string){await this.actor(id);const[userCount,roomCount,messageCount,auditCount]=await Promise.all([this.users.count(),this.rooms.count(),this.messages.count({where:{deletedAt:IsNull()}}),this.audits.count()]);const recent=await this.audits.find({order:{createdAt:'DESC'},take:8});return{userCount,roomCount,messageCount,auditCount,recent};}
async listUsers(id:string,q=''){await this.actor(id);return this.users.createQueryBuilder('u').leftJoinAndSelect('u.rank','rank').where(q?'LOWER(u.username) LIKE LOWER(:q)':'1=1',{q:`%${q}%`}).orderBy('rank.starCount','DESC').addOrderBy('u.username','ASC').take(100).getMany();}
async setRank(id:string,targetId:string,d:SetUserRankDto){const a=await this.actor(id);this.permit(a,'admin.users');const t=await this.users.findOne({where:{id:targetId},relations:{rank:true}});if(!t)throw new NotFoundException('Kullanıcı bulunamadı.');assertCanGrantRank(a,t,d.starCount);const r=await this.ranks.findOneBy({starCount:d.starCount});if(!r)throw new NotFoundException('Rütbe bulunamadı.');t.rankId=r.id;await this.users.save(t);await this.audits.save(this.audits.create({actorId:a.id,targetUserId:t.id,roomId:null,messageId:null,action:'admin.rank.change',reason:null,metadata:{from:t.rank.starCount,to:r.starCount}}));return{...t,rank:r};}
async updateRank(id:string,stars:number,d:UpdateRankDto){const a=await this.actor(id);this.permit(a,'admin.ranks');if(stars===27)throw new ForbiddenException('⭐27 Site Sahibi korumalıdır.');if(stars>=a.rank.starCount)throw new ForbiddenException('Kendi rütbene eşit/yüksek rütbeyi düzenleyemezsin.');const r=await this.ranks.findOneBy({starCount:stars});if(!r)throw new NotFoundException();if(d.permissions){for(const v of Object.values(d.permissions))if(typeof v!=='boolean')throw new ForbiddenException('İzin değerleri boolean olmalı.');}Object.assign(r,d);return this.ranks.save(r);}
async listRooms(id:string){await this.actor(id);return this.rooms.find({order:{createdAt:'ASC'}})}async updateRoom(id:string,roomId:string,d:UpdateRoomDto){const a=await this.actor(id);this.permit(a,'admin.rooms');const r=await this.rooms.findOneBy({id:roomId});if(!r)throw new NotFoundException();Object.assign(r,d);return this.rooms.save(r)}

async content(id:string,q=''){const a=await this.actor(id);this.permit(a,'admin.content');const qb=this.wallPosts.createQueryBuilder('p').withDeleted().leftJoin(User,'u','u.id=p.author_id').select(['p.id AS id','p.body AS body','p.created_at AS "createdAt"','p.deleted_at AS "deletedAt"','p.author_id AS "authorId"','u.username AS username']).orderBy('p.created_at','DESC').limit(100);if(q.trim())qb.where('(LOWER(p.body) LIKE LOWER(:q) OR LOWER(u.username) LIKE LOWER(:q))',{q:`%${q.trim()}%`});return qb.getRawMany();}
async removeContent(id:string,postId:string,reason?:string){const a=await this.actor(id);this.permit(a,'admin.content');const p=await this.wallPosts.findOne({where:{id:postId},withDeleted:true});if(!p)throw new NotFoundException('Paylaşım bulunamadı.');if(p.deletedAt)return{ok:true,id:postId,alreadyDeleted:true};await this.wallPosts.softDelete(postId);await this.audits.save(this.audits.create({actorId:a.id,targetUserId:p.authorId,roomId:null,messageId:null,action:'admin.wall.delete',reason:reason?.trim()||'Admin içerik moderasyonu',metadata:{postId}}));return{ok:true,id:postId};}
async audit(id:string){const a=await this.actor(id);this.permit(a,'room.audit');return this.audits.find({order:{createdAt:'DESC'},take:100})}async getSettings(id:string){await this.actor(id);return this.settings.find({order:{key:'ASC'}})}async setSetting(id:string,d:UpdateSettingDto){const a=await this.actor(id);this.permit(a,'admin.settings');return this.settings.save(this.settings.create({key:d.key,value:d.value}))}}
