import {BadRequestException,Injectable,UnauthorizedException} from '@nestjs/common';
import {InjectRepository} from '@nestjs/typeorm';import {JwtService} from '@nestjs/jwt';import {DataSource,Repository} from 'typeorm';import * as bcrypt from 'bcryptjs';import {createHash,randomBytes} from 'node:crypto';
import {User} from './user.entity';import {Rank} from '../ranks/rank.entity';import {AuthSession} from './auth-session.entity';import {SiteConfigService} from '../site-config/site-config.service';
@Injectable() export class AuthService{
 constructor(@InjectRepository(User)private users:Repository<User>,@InjectRepository(Rank)private ranks:Repository<Rank>,@InjectRepository(AuthSession)private sessions:Repository<AuthSession>,private jwt:JwtService,private siteConfig:SiteConfigService,private db:DataSource){}
 private publicUser(user:User){return{id:user.id,username:user.username,isGuest:user.isGuest,rank:user.rank}}
 private hash(raw:string){return createHash('sha256').update(raw).digest('hex')}
 private async access(user:User){return this.jwt.signAsync({sub:user.id,username:user.username},{expiresIn:'15m'})}
 private makeRefresh(){const refreshToken=randomBytes(48).toString('base64url');return{refreshToken,tokenHash:this.hash(refreshToken),expiresAt:new Date(Date.now()+30*24*60*60*1000)}}
 private async issue(user:User,meta?:{userAgent?:string;ip?:string}){const r=this.makeRefresh();const session=this.sessions.create({userId:user.id,tokenHash:r.tokenHash,expiresAt:r.expiresAt,revokedAt:null,lastUsedAt:null,userAgent:meta?.userAgent?.slice(0,300)||null,ipAddress:meta?.ip?.slice(0,64)||null});await this.sessions.save(session);return{accessToken:await this.access(user),refreshToken:r.refreshToken,refreshExpiresAt:r.expiresAt,user:this.publicUser(user)}}
 async register(username:string,password:string,meta?:any){if(await this.users.exists({where:{username}}))throw new BadRequestException('Bu kullanıcı adı kullanımda');const rank=await this.ranks.findOneByOrFail({starCount:1});const user=this.users.create({username,passwordHash:await bcrypt.hash(password,12),isGuest:false,rankId:rank.id,rank});await this.users.save(user);return this.issue(user,meta)}
 async login(username:string,password:string,meta?:any){const user=await this.users.findOne({where:{username},relations:{rank:true}});if(!user?.passwordHash||!(await bcrypt.compare(password,user.passwordHash)))throw new UnauthorizedException('Kullanıcı adı veya parola hatalı');return this.issue(user,meta)}
 async guest(nickname:string,meta?:any){if(!await this.siteConfig.enabled('guest.enabled',true))throw new BadRequestException('Misafir girişi şu anda kapalı');const rank=await this.ranks.findOneByOrFail({starCount:1});const suffix=randomBytes(4).toString('hex').slice(0,5);const user=this.users.create({username:`${nickname}-${suffix}`.slice(0,32),passwordHash:null,isGuest:true,rankId:rank.id,rank});await this.users.save(user);return this.issue(user,meta)}
 async refresh(raw:string|undefined,meta?:any){if(!raw)throw new UnauthorizedException('Oturum bulunamadı');const tokenHash=this.hash(raw);const rotated=await this.db.transaction(async em=>{const repo=em.getRepository(AuthSession);const session=await repo.createQueryBuilder('s').setLock('pessimistic_write').leftJoinAndSelect('s.user','user').leftJoinAndSelect('user.rank','rank').where('s.token_hash=:tokenHash',{tokenHash}).getOne();if(!session||session.revokedAt||session.expiresAt.getTime()<=Date.now())throw new UnauthorizedException('Oturum süresi dolmuş');const now=new Date();session.revokedAt=now;session.lastUsedAt=now;await repo.save(session);const r=this.makeRefresh();await repo.save(repo.create({userId:session.userId,tokenHash:r.tokenHash,expiresAt:r.expiresAt,revokedAt:null,lastUsedAt:null,userAgent:meta?.userAgent?.slice(0,300)||null,ipAddress:meta?.ip?.slice(0,64)||null}));return{user:session.user,...r}});return{accessToken:await this.access(rotated.user),refreshToken:rotated.refreshToken,refreshExpiresAt:rotated.expiresAt,user:this.publicUser(rotated.user)}}
 async logout(raw:string|undefined){if(!raw)return{ok:true};const session=await this.sessions.findOneBy({tokenHash:this.hash(raw)});if(session&&!session.revokedAt){session.revokedAt=new Date();await this.sessions.save(session)}return{ok:true}}
 async me(id:string){const user=await this.users.findOne({where:{id},relations:{rank:true}});if(!user)throw new UnauthorizedException();return this.publicUser(user)}
}
