import {BadRequestException,ForbiddenException,Injectable,NotFoundException} from '@nestjs/common';
import {InjectRepository} from '@nestjs/typeorm';import {EntityManager,Repository} from 'typeorm';import {randomUUID} from 'node:crypto';import {MediaAsset} from './media.entity';
type Purpose=MediaAsset['purpose']; const IMAGE=new Set(['image/jpeg','image/png','image/webp','image/gif']);
function sniff(b:Buffer):string|null{if(b.length<12)return null;if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return'image/jpeg';if(b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return'image/png';if(b.subarray(0,4).toString()==='GIF8')return'image/gif';if(b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP')return'image/webp';if(b.subarray(4,8).toString()==='ftyp')return'video/mp4';return null;}
@Injectable() export class MediaService{constructor(@InjectRepository(MediaAsset)private repo:Repository<MediaAsset>){}
 private cfg(){const url=process.env.SUPABASE_URL?.replace(/\/$/,'');const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const bucket=process.env.SUPABASE_MEDIA_BUCKET||'gogochat-media';if(!url||!key)throw new BadRequestException('Media storage yapılandırılmamış');return{url,key,bucket};}
 async upload(userId:string,purpose:Purpose,file:Express.Multer.File){if(!file?.buffer?.length)throw new BadRequestException('Dosya gerekli');const mime=sniff(file.buffer);if(!mime)throw new BadRequestException('Desteklenmeyen veya geçersiz dosya');if(['avatar','cover','gallery'].includes(purpose)&&!IMAGE.has(mime))throw new BadRequestException('Bu alanda yalnız görsel kullanılabilir');if(!IMAGE.has(mime)&&mime!=='video/mp4')throw new BadRequestException('Dosya türü desteklenmiyor');const max=IMAGE.has(mime)?8*1024*1024:15*1024*1024;if(file.size>max)throw new BadRequestException(`Dosya en fazla ${IMAGE.has(mime)?8:15} MB olabilir`);const ext:{[k:string]:string}={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','video/mp4':'mp4'};const path=`users/${userId}/${purpose}/${randomUUID()}.${ext[mime]}`;const c=this.cfg();const r=await fetch(`${c.url}/storage/v1/object/${c.bucket}/${path}`,{method:'POST',headers:{Authorization:`Bearer ${c.key}`,apikey:c.key,'Content-Type':mime,'x-upsert':'false'},body:new Uint8Array(file.buffer)});if(!r.ok)throw new BadRequestException('Dosya depolamaya yüklenemedi');const publicUrl=`${c.url}/storage/v1/object/public/${c.bucket}/${path}`;try{return await this.repo.save(this.repo.create({ownerId:userId,purpose,storageKey:path,publicUrl,mimeType:mime,sizeBytes:file.size,attachedKind:null,attachedId:null,attachedAt:null}));}catch(e){await this.removeObject(path).catch(()=>undefined);throw e;}}
 async claim(manager:EntityManager,userId:string,id:string,purpose:Purpose,kind:string,attachedId:string){const repo=manager.getRepository(MediaAsset);const a=await repo.createQueryBuilder('a').setLock('pessimistic_write').where('a.id=:id AND a.deletedAt IS NULL',{id}).getOne();if(!a)throw new NotFoundException('Medya bulunamadı');if(a.ownerId!==userId)throw new ForbiddenException('Bu medya sana ait değil');if(a.purpose!==purpose)throw new BadRequestException('Medya amacı uyuşmuyor');if(a.attachedId)throw new BadRequestException('Medya zaten kullanılıyor');a.attachedKind=kind;a.attachedId=attachedId;a.attachedAt=new Date();return repo.save(a);}
 async remove(userId:string,id:string){const a=await this.repo.findOne({where:{id}});if(!a)throw new NotFoundException('Medya bulunamadı');if(a.ownerId!==userId)throw new ForbiddenException();if(a.attachedId)throw new BadRequestException('Kullanımdaki medya doğrudan silinemez');await this.removeObject(a.storageKey);await this.repo.softDelete(id);return{ok:true};}
 async removeObject(path:string){const c=this.cfg();const r=await fetch(`${c.url}/storage/v1/object/${c.bucket}/${path}`,{method:'DELETE',headers:{Authorization:`Bearer ${c.key}`,apikey:c.key}});if(!r.ok&&r.status!==404)throw new Error('storage delete failed');}
}
